baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Studio Domu'
theme = 'studio-domu'

googleAnalytics = "G-E5HQ2GCQST"
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false

[params]
    email = "hello@studiodomu.com"
    footer = "All rights reserved – Intro by <a class=\"link\" href=\"https://cans.one/\">Cans One Studio</a>."
    social = [
    { name = "Instagram", url = "https://www.instagram.com/studiodomu/", icon = "instagram" },
    ]

[menu]
  [[menu.main]]
    name = "Projects"
    url = "#projects-section"
    weight = 10
  [[menu.main]]
    name = "Behind Domu"
    url = "#behind-domu-section"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "#about-section"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "#contact-section"
    weight = 40
