baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Studio Domu'

[params]
  google_fonts = [
    ["Syne", "400, 700, 900"],
    ["Poppins", "300, 400, 500, 600, 700"]
  ]

  heading_font = "Syne"
  body_font = "Poppins"