name = 'Studio Domu Theme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme for Studio Domu'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If the theme has a single author
[author]
  name = 'Andrea Iorio'
  homepage = 'https://andreaiorio.me'
